---
title: "Evictions in Regulated Affordable Housing, Multnomah County"
output: flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
library(flexdashboard)
library(fontawesome)
library(plotly)
library(leaflet)
source("SubReg_Multnomah.R")
source("geocoding and map.R")
```
Home
================

## Column 1: Map Area {data-width="600"}

### Evictions in Multnomah County, January 2019 - October 2022

```{r map}
                
property_map

```

> Source: Evicted in Oregon

## Column 2: Charts {data-width="400"}

### Total Eviction Filings

```{r box: total feds}
all_feds <- sum(ot_outcome$total_feds)
valueBox(prettyNum(all_feds, big.mark = ","),
         caption = 'Total Eviction Filings, January 2019 - October 2022'
         )
```

### Eviction Filings Over Time

```{r chart: time series}

feds_time_bar <- feds_time_plot +
  geom_bar() +
  scale_x_date(breaks = seq(as.Date("2019-01-02"), as.Date("2022-10-13"),
                            by="3 months"), date_labels = "%b %Y") +
  scale_y_continuous(limits = c(0,90), expand = c(0.02, 0.02)) +
  labs(x="Month", y="Number of Filings", fill="Owner Type") +
  #scale_fill_manual(
  #breaks = c("for profit", "multiple", "nonprofit", "public entity", "NA"),
  #labels = c("For Profit", "Multiple", "Nonprofit", "Public Entity", "NA")) +
  theme(
    axis.text.x = element_text(angle = 90),
    panel.grid = element_blank()
  )

ggplotly(feds_time_bar)

```

### Filings That Ended in Eviction

```{r chart: pct evicted}

pct_evicted_bar <- ot_pct_evicted %>% #
  ggplot(aes(x = owner_type,
             y = pct_evicted,
             fill = factor(owner_type),
             label = scales::percent(pct_evicted))) +
  scale_y_continuous(labels = scales::percent, limits = c(0,1)) +
  geom_col() +
  geom_text(aes(y = pct_evicted + 0.035),
            position = position_dodge2(0.9),
            fontface = "bold") +
  labs(x = "Owner Type", y = "Percent of Filings Ending in Eviction") +
  theme(
    legend.position = "none",
    panel.grid = element_blank())

ggplotly(pct_evicted_bar)
```

Tables
================

## Column 1: Tables {.tabset}

--------------

### Property Statistics

```{r table setup, include=FALSE}

source("Tables.R")

```

```{r table: properties}

property_stats_format

```

### Owner Statistics

```{r table: owners}

owner_stats_format

```

### Management Statistics

```{r table: mgmt}

management_stats_format

```