---
title: "USP 410/510: Urban Informatics"
subtitle: "Data Visualization w/ ggplot2"
author: "Liming Wang"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  xaringan::moon_reader:
    css: "example.css"
    seal: yes
    nature:
      highlightStyle: github
      beforeInit: "macros.js"
---

```{r setup, include=F}
knitr::opts_chunk$set(message=FALSE, warning=F, echo=F)
options(width = 2000)
options(repos="https://cran.rstudio.com")
```

# What is Markdown?

Markdown is a way to write content for the web. It’s written in what people like to call “plaintext”, which is exactly the sort of text you’re used to writing and seeing. Plain text is just the regular alphabet, with a few familiar symbols, like asterisks ( * ) and backticks ( ` ).

Formatting text in Markdown has a very gentle learning curve. It doesn’t do anything fancy like change the font size, color, or type. All you have control over is the display of the text—stuff like making things bold, creating headers, and organizing lists.

---

# Rmarkdown

RMarkdown is a dialect of markdown - a flavor of markdown that understands R programming language, thus allows users to control a markdown document with R, such as inserting resulting figures, tables, and other outputs generated by R.

---

# What Rmarkdown can do?

- Rmarkdown Gallery: https://rmarkdown.rstudio.com/gallery.html
- R Markdown gallery: https://r-markdown-gallery.com/

---

# Why R Markdown?

- Reproducibility
  - literal programming: combine programming and writing
- Versatile/Programmable

---

# Using RMarkdown

- markdown tutorial: https://www.markdowntutorial.com/
- R Markdown tutorial: https://rmarkdown.rstudio.com/lesson-1.html
- R Markdown Cheatsheet: https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf

---

# Version Control / Git

- Pain point
  - Share code/data for collaborative/parallel work
  - Ability to undo/revert experimental code/document/data
  - Think Google docs + track change for your code & data
- git/github is the most popular option at this point
  - The learning curve is steep, but smoothed by tools like RStudio (embedded support) and GitHub desktop
  - [Datacamp Course: Introduction to Git](https://app.datacamp.com/learn/courses/introduction-to-git)
  - [Happy Git and GitHub for the UseR](https://happygitwithr.com/)
  - [Github quick start guide](https://docs.github.com/en/get-started/quickstart)
  - Tutorials on youtube: https://www.youtube.com/results?search_query=learning+git