---
title: 'USP410/510 Lab 2: tidy data & tidy workflow'
author: "Liming Wang"
date: ""
output: 
  learnr::tutorial:
    progressive: true
    allow_skip: true
runtime: shiny_prerendered

---


```{r setup, include=FALSE}
library(learnr)

tutorial_options(exercise.timelimit = 60)
knitr::opts_chunk$set(error = TRUE, exercise=TRUE)
```

## Workflow within RStudio

There are two main ways one can work within RStudio:

1. Test and play within the interactive R console then copy code into a .R file to run later.
   *  This works well when doing small tests and initially starting off.
   *  It quickly becomes laborious
2. Start writing in a .R file and use RStudio's short cut keys for the Run command to push the current line, selected lines or modified lines to the interactive R console.
   * This is a great way to start; all your code is saved for later
   * You will be able to run the file you create from within RStudio or using R's `source()`  function.


> ## Tip: Running segments of your code
>
> RStudio offers you great flexibility in running code from within the editor
> window. There are buttons, menu choices, and keyboard shortcuts. To run the
> current line, you can
> 1. click on the `Run` button above the editor panel, or
> 2. select "Run Lines" from the "Code" menu, or
> 3. hit Ctrl+Return in Windows or Linux or Command+Return on Mac OS.
> (This shortcut can also be seen by hovering
> the mouse over the button). To run a block of code, select it and then `Run`.
> If you have modified a line of code within a block of code you have just run,
> there is no need to reselect the section and `Run`, you can use the next button
> along, `Re-run the previous region`. This will run the previous code block
> including the modifications you have made.

# Best practice of managing your project with RStudio

- Create a project for self-containing work, e.g. this class, your GRA work;
- Create separate directories for data, docs, and R code, plot outputs, etc;
- Use path relative to the root of your project throughout your project (or use the `here` package);
- Avoid saving and restoring workspace/environment.

## References
- [Project-oriented workflow](https://www.tidyverse.org/blog/2017/12/workflow-vs-script/)
- [Project Management With RStudio](http://swcarpentry.github.io/r-novice-gapminder/02-project-intro/)
- [RStudio IDE cheatsheet](https://raw.githubusercontent.com/rstudio/cheatsheets/main/rstudio-ide.pdf)

